### ISSUE TITLE
Explain how to run web-less applications

### ISSUE THREAD

**Issue by ksol** [Scalingo/documentation#930]
Some customers are interrested in running applications not exposed to the web; while it's possible it's not explained in the doc nor is it easy to guess how (having a dummy `web` container scaled at 0)

**Comment by EtienneM** [comment]
@ksol Can you quickly explain how to declare this dummy `web` container?

**Comment by ksol** [comment]
I think it's having any command `web: echo yes` and having that container scaled at 0. I should have linked the intercom conv.

**Comment by EtienneM** [comment]
@Soulou do you know what is the best way to run a web-less application on Scalingo? I doubt that `web: echo yes` works 🤔

**Comment by Soulou** [comment]
If we want people to do it automously, we have to modify our API. Since today the only method for this is:

1. Contact the support
2. Ask for a non-web app
3. Operator create the `web` container type of the app before the first successful deployment and scale it to 0
4. User deploy it's app, no `web` container will be started, deployment will be a success
5. User can scale up the `worker` for instance.

**Comment by Soulou** [comment]
With our API it's possible to scale before the first deployment `web` containers to 0, but our CLI doesn't allow to do it, running `scalingo -a my-app scale web:0`
